apache/arrow-site

README.md
build-and-deploy.sh

This change enables the use of [GitHub deploy keys](https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys), which are tied to a repository and not an individual (in contrast with personal access tokens). Once this is merged, we can add a key pair to the repository settings in GitHub and Travis (INFRA may be required to do one or both of those) and then commits to the website source in the `master` branch will automatically build and push the generated static site to the `asf-site` branch.

ARROW-6260: [Website] Use deploy key on Travis to build and push to asf-site

---

powered_by.md

This add TileDB to the "Powered by" section of the website. TileDB was added in alphabetical order with two new links.

Add TileDB to "Powered by" section

---

_posts/2020-07-27-cpp-build-simplification.md

This needs a title and a conclusion paragraph. Feedback and edits greatly appreciated.

ARROW-9190: [Website][C++] Add blog post on efforts to make building lighter and easier

---

powered_by.md

This follows the email thread "Introducing Cylon" [1]. 
As discussed in the mail thread, we would like to add Cylon [2] to the "powered-by Arrow" list. 
Best 
[1] https://mail-archives.apache.org/mod_mbox/arrow-dev/202007.mbox/%3cCANCoaU4ZSNkhG=fXm=cd5ASoHYjW7Y6pc2mUQSewaafyJXUjjg@mail.gmail.com%3e
[2] https://cylondata.org/docs/

Adding Cylon to powered-by list

---

powered_by.md

This PR adds our network telemetry engine [VAST](https://github.com/tenzir/vast) to the powered-by page.

Add VAST to powered-by page

---

install.md

Disclaimer: I did not test that these work, just find-replaced the URLs.
There are more bintray URLs on the per-release pages (which I believe are created automatically as a post-release task), but I don't know how to begin to fix those.

ARROW-12356: [Website] Update install page instructions to point to artifactory

---

_posts/2019-02-04-datafusion-donation.md
_posts/2020-10-27-rust-2.0.0-release.md
_posts/2021-04-12-ballista-donation.md

Moving the Rust code to new repos broke a few links in blog posts.

MINOR: Fix broken links to Rust projects

---

use_cases.md

Currently, the page: https://arrow.apache.org/use_cases/ contains a python link for "Feather" with python using "https://arrow.apache.org/docs/python/feather.html%20%7D%7D" which redirects to a 404.
Instead, it seems that we should be using the following: "https://arrow.apache.org/docs/python/feather.html".

Removing extra "}}" from the Feather Python link.

---

_release/5.0.0.md

This fixes the problem with the Rust committers described in the comment in #131

[Website] Fix Rust committers in release note for 5.0.0

---

_posts/2021-07-20-5.0.0-rs-release.md

What was meant to be comments on https://github.com/apache/arrow-site/pull/128  were rendering accidentally:

Stop comment rendering on 5.0.0 Rust blog

---

_includes/header.html

Following the advice from https://lists.apache.org/thread.html/r5c9341fe5360ae249532724da2bf92bd2ed661d1c58f599212e82107%40%3Cdev.arrow.apache.org%3E.

MINOR: [Website] Add datafusion to homepage top banner

---

release-announcement-template.md

This updates the Rust release details in the blog post template, as a follow-up to the changes in [ARROW-12701](https://issues.apache.org/jira/browse/ARROW-12701) and  #127

[Website] Update Rust release details info in release blog post template

---

_posts/2021-11-8-datafusion-6.0.0.md

Companion blog to the 6.0.0 release that we are working on at https://github.com/apache/arrow-datafusion/pull/1253
Comments / suggestions very welcome! I just did a brain dump of what came to mind
cc @houqp @Dandandan @Jimexist

Add DataFusion 6.0.0 blog

---

.github/workflows/devdocs.yml

Small follow-up on https://github.com/apache/arrow-site/pull/173, so you can trigger the workflow manually from the github UI if needed

ARROW-1299: [Docs] Allow trigger nightly devdocs job manually

---

docs/_static/versions.json

This ensures that the new dev docs will appear in the version dropdown (eg if you are on the stable docs).

ARROW-1299: [Doc] Add the dev version to the version dropdown

---

_posts/2022-02-14-datafusion-7.0.0.md
_posts/2022-02-17-datafusion-7.0.0.md

related: https://github.com/apache/arrow-datafusion/issues/1587
based on crowd sourced content https://docs.google.com/document/d/17uB1GIN58xOehQP5XpJH8J3qA7KDS1WQJzyHzW7L1kU/edit?usp=sharing

ARROW-15683: [Website] [DataFusion] DataFusion 7.0.0 blog post

---

_data/committers.yml

Reference: https://lists.apache.org/thread/n26odmwlv7vgxvp9xboql0txk00nyypx
Add new committers to https://arrow.apache.org/committers/ page
@tustvold, @xudong963, @yjshen and @liukun4515  can you please supply your desired "affiliation" and verify this information is correct?

ARROW-15902: [Website] Add new committers:  Raphael Taylor-Davies,  Wang Xudong, Yijie Shen, Kun Liu

---

powered_by.md

Summary:
- As it stands, this PR only touches the `powered_by` page, linking it to the `visual_identity` page and uses one of the new logo files for that page. 
- There are two additional uses of the older files on the site: the site banner on the main page uses `arrow-inverse.png`, and the navbar header uses `arrow-inverse-300px.png`. I could switch those too, but I'm not sure there's value in that: the new files have more whitespace surrounding them, so I'd have to end up recreating exact replicas of the existing files if we wanted to preserve the (IMO very nice) tight vertical spacing on the site banner and the navbar.
As far as I can tell this is all that's needed?

ARROW-15786: [Website] Tidy use of and linking to Arrow logo

---

_data/committers.yml

Adds @viirya  to to list at https://arrow.apache.org/committers/
Reference: https://lists.apache.org/thread/kyrlog8klo6qf4n1p1s2vo464mr22rf2
@viirya  can you please tell me what affiliation you would like listed?

Add Liang-Chi Hsieh to list of committers

---

_posts/2021-10-22-6.0.0-release.md

https://arrow.apache.org/blog/2021/11/04/6.0.0-release/

ARROW-16583: [Website] Fix broken links in 6.0.0-release post

---

_posts/2022-08-01-9.0.0-release.md
_posts/2022-08-16-9.0.0-release.md

PR to start adding the blog post information for the Release 9.0.0

Version 9.0.0 release blog post

---

_data/committers.yml

While looking at https://arrow.apache.org/committers/
I noticed these still said TBD so I filled them in with what I think the affiliation are for @tustvold  and @liukun4515

Update affliation for Kun Liu and Raphael Taylor-Davis

---

install.md

I noticed that the links to the Rust crate docs and Julia repo on the install page didn't work. This PR makes them clickable.

MINOR: Link to Rust crate documentation and Julia package repository

---

_data/committers.yml

Add Dan Harris @thinkharderdev to the list of committers on https://arrow.apache.org/committers/, per https://lists.apache.org/thread/rcbmf581s3l5khhhp5ktt05lv542hbbr

[MINOR] Add thinkharderdev to list of committers

---

_posts/2022-10-05-arrow-parquet-encoding-part-1.md
_posts/2022-10-08-arrow-parquet-encoding-part-2.md

Related to https://issues.apache.org/jira/browse/ARROW-17907
As noticed by @drin in https://github.com/apache/arrow-site/pull/247#discussion_r996736307 the formatting is kind of crappy:
This PR improves https://arrow.apache.org/blog/2022/10/05/arrow-parquet-encoding-part-1/ and https://arrow.apache.org/blog/2022/10/08/arrow-parquet-encoding-part-2/ with better formatting:

[MINOR] Improve formatting of json examples + links in nested parquet blogs

---

.github/workflows/deploy.yml

In preparation for publishing the DataFusion Python documentation

ARROW-18418: [WEBSITE] Do not delete /datafusion-python

---

_includes/header.html
arrow.rdf
community.md
faq.md

This PR is part of the work to update the documentation as we are moving from Jira issue tracker to GitHub issues:
https://github.com/apache/arrow/issues/14822
closes #284

GH-284: Update Apache Arrow website references to Jira

---

_posts/2023-01-18-11.0.0-release.md
_posts/2023-01-25-11.0.0-release.md

PR to start adding the blog post information for the Release 11.0.0
With the movement from JIRA to GitHub issues here a couple of links to help finding the issues for 11.0.0.
11.0.0 RC 0 changelog so far can be found on this commit:
https://github.com/apache/arrow/commit/6d0f608d1491ef00cd8adfdb030fffb6f7605104
The 11.0.0 milestone with all the GitHub closed issues can be found here:
https://github.com/apache/arrow/milestone/1?closed=1

[Website] Version 11.0.0 blog post

---

_posts/2023-01-26-rust-32.0.0.md
_posts/2023-02-14-rust-32.0.0.md

~This is a pretty rough first draft, but wanted to get something up to solicit feedback~
Update: this is ready for review

[Website] January 2023 Rust Apache Arrow 32.0.0 Highlights

---

_posts/2023-02-14-rust-32.0.0.md

The publish job did not complete  and thus https://github.com/apache/arrow-site/pull/305 is not yet visible
https://github.com/apache/arrow-site/actions
```
https://github.com/apache/arrow-site/actions/runs/4175072450/jobs/7229492372#step:10:63Run git config user.name "$(git log -1 --pretty=format:%an)"
From https://github.com/apache/arrow-site
* [new branch]              asf-site   -> deploy/asf-site
* [new branch]              master     -> deploy/master
Switched to a new branch 'asf-site'
branch 'asf-site' set up to track 'deploy/asf-site'.
[asf-site 5e2e8da16ba] Updating built site (build c4fe669417f1d241fdfc16b6ee9876c2fa18fa70)
44 files changed, 726 insertions(+), 387 deletions(-)
create mode 100644 blog/2023/02/13/rust-32.0.0/index.html
To https://github.com/apache/arrow-site.git
! …
```

Minor: minor changes to rust blog post to fix publish job

---

committers.md

**NOTE** This is a work in progress and does not necessarily represent the PMC stance yet. 
It has come to my attention recently that it may not be clear what criteria we use to determine if we should invite someone new to be a committer. 
I would like to add some clarity that our project is open to new contributors, and that if you want to become more deeply involved with the project, here are the kinds of activities that maintainers do.
Also, I of course want to encourage more people to contribute to our project, and I hope this will inspire some to do so
Add a "Becoming a committer" section to https://arrow.apache.org/committers/ 
The content partially came from a discussion on the PMC mailing list, and I would like to thank @nealrichardson @westonpace and @kou  for their help so far. …

[Website] Committer expectations and process

---

docs/r/news/index.html

The docs show 11.0.0 but since the release we've bumped the version to 11.0.0.2.  I haven't run any scripts here, I've just manually edited the HTML; is this OK?

[Website] Change R version from 11.0.0 to 11.0.0.2

---

.github/workflows/deploy.yml

As part of apache/arrow#31142 and in response to the [recent rename of the `apache/arrow-site` repository default branch to `main`](https://issues.apache.org/jira/browse/INFRA-24242), this pull request removes support for triggering the website deployment workflow (`.github/workflows/deploy.yml`) on pushes to a branch with the name "master".
To qualify these changes, I verified that:
1. Pushing these changes to the `main` branch of `mathworks/arrow-site` [triggered the `deploy.yml` workflow as expected](https://github.com/mathworks/arrow-site/actions/runs/4296490412/jobs/7488276762).
2. The workflow step "Configure for GitHub Pages on push to main or master branch" has been renamed to "Configure for GitHub Pages on push to main branch"
3. The `deploy.yml` is no longer being triggered when …

GH-31412: [Website] Remove support for triggering GitHub Actions apache/arrow-site website deployment workflow when pushing to master

---

README.md

This pull request adds a link to the [Ruby End-Of-Life (EOL) schedule](https://www.ruby-lang.org/en/downloads/branches/) to the [Prerequisites section of the `README.md` for `apache/arrow-site`](https://github.com/apache/arrow-site#prerequisites). It also spells out the acronym EOL as End-Of-Life to avoid any confusion.
N/A
N/A
N/A
Closes apache/arrow-site#329

GH-329: [Website] Add a link to the Ruby End-Of-Life (EOL) schedule in the Prerequisites section of README.md

---

.github/workflows/deploy.yml
.nvmrc
package-lock.json
package.json

This pull request modifies the `apache/arrow-site` website deployment workflow (`.github/workflows/deploy.yml`) to use the latest LTS version of Node.js and Webpack 5.75.0 to work around the build issue described in #325.
To qualify these changes, I:
1. Submitted these changes to the `main` branch of the `mathworks/arrow-site` fork in order to trigger the `gh-pages` deployment workflow. I then selected `gh-pages` as the GitHub Pages deployment branch and verified that the site was deployed as expected to https://mathworks.github.io/arrow-site/. For an example of a successful workflow run, see: https://github.com/mathworks/arrow-site/actions/runs/4313253336/jobs/7524824999.
2. I inspected the GitHub Actions workflow steps to ensure there are no errors.
1. While qualifying with the [fork …

GH-325: [Website] Update website deployment script to use latest LTS version of Node.js and Webpack 5.75.0

---

community.md

Closes https://github.com/apache/arrow/issues/34255

GH-34255: Add information about meetings to Community page

---

.github/workflows/deploy.yml

Per @kou 's suggestion https://github.com/apache/arrow-site/pull/336#issuecomment-1478619475
We are now serving datafusion content from the datafusion-repo -- see https://github.com/apache/arrow-datafusion/issues/5500

[Website] Clean up unecessary skip of `datafusion` and `datafusion-python`

---

community.md

As discussed on the 2023-02-01 Arrow Community Meeting, this expands the text around tag uses on the mailing list. I tried to keep it short so let me know if there areas that would be better expanded (such as voting).
Closes https://github.com/apache/arrow/issues/33989

Expand text about MLs on Community page

---

powered_by.md

cc @zeroshade :) I hope it's ok if we can add ourselves here. We are about 50% into the migration and some parts are already operational. Would love also to do a shared blog and why we decided to use it at some point.

Add CloudQuery to powered by arrow

---

docs/r/news/index.html

The Changelog for the R docs wasn't updated in the last release; I think this is due to the timing of updates, and things being merged after the release scripts were ran.
Fix apache/arrow#35106

GH-35106: [R] Docs for 11.0.0 changelog not updated

---

_posts/2023-05-02-12.0.0-release.md
install.md

Fixes apache/arrow#35625
This also adds a note about dropping support for Ubuntu 18.04 to release announce blog post.

GH-35625: [Website] Update install information for 12.0.0

---

_posts/2023-06-13-12.0.1-release.md

PR for blog post information for the Release 12.0.1
The 12.0.1 milestone with all the GitHub closed issues can be found here:
https://github.com/apache/arrow/milestone/54?closed=1
And the published release page: https://arrow.apache.org/release/12.0.1.html

[Website] Version 12.0.1 blogpost

---

_data/committers.yml

Update the website roster to list @baumgold  as PMC, per https://lists.apache.org/thread/8zj6z6sky13jsdrb7hbybkwkd3vg8qz9

[WEBSITE]: Update Role of Ben Baumgold to PMC on committers list

---

_posts/2023-06-13-nanoarrow-0.120-release.md

Rendered version at: https://github.com/paleolimbot/arrow-site/blob/nanoarrow-0-2-0-release/_posts/2023-06-13-nanoarrow-0.120-release.md

Add announcement for nanoarrow 0.2.0 release

---

_posts/2023-06-24-datafusion-25.0.0.md

Typo in https://github.com/apache/arrow-site/pull/370 -- thanks to @tustvold  for the spot

[WEBSITE] Minor: Fix typo on DataFusion 26 blog

---

_posts/2023-06-24-datafusion-25.0.0.md

@stuartcarnie noticed this link was incorrect, it should point at https://www.synnada.ai/blog/general-purpose-stream-joins-via-pruning-symmetric-hash-joins

[WEBSITE]: Minor fix blog link on DataFusion 26 blog

---

_includes/header.html

The link on https://arrow.apache.org/  for the Rust documentation 
Goes to https://docs.rs/crate/arrow/ a hosted version of the crates.io page:
Go to the standard rust docs: https://docs.rs/arrow/latest which I think is what I would expect when I click on a documentation link

Update docs.rs link

---

_includes/header.html

This PR adds a link in the "Subprojects" dropdown menu for nanoarrow and links to the nanoarrow documentation ( https://arrow.apache.org/nanoarrow ).
I *think* this is the appropriate place for the link...nanoarrow is not *really* a language binding (since it also has language bindings for things like R that already have an Arrow implementation). I'm happy to link from somewhere else, too.

Add Subproject dropdown item for nanoarrow

---

_data/committers.yml

Closes https://github.com/apache/arrow-site/issues/383
The committers page has links to the apache phonebook and thus the alias should be the apache user name (rather than github username): https://arrow.apache.org/committers/
@pitrou  noticed that there were some entries that used the github names instead
Correct committer data for `jakevin`, `avantgardner`, `akurmustafa` and `wayne`
Note: I will make a separate PR to add an entry for Gang Wu
cc @waynexia @avantgardnerio @mustafasrepo @jackwener

[Website]: Correct committer data for `jakevin`, `avantgardner`, `akurmustafa` and `wayne`

---

_posts/2023-08-24-13.0.0-release.md

I did forget to update the milestone for the 13.0.0 release.

MINOR: [Website] Fix milestone link for 13.0.0 blogpost

---

.github/workflows/devdocs.yml

The underlying crossbow job and thus artifact name, changed causing the job to fail. This PR adds a wild card to prepare for future changes in ubuntu version used for the doc as well as restoring function. Tested in my fork https://github.com/apache/arrow-site/actions/runs/6116092199/job/16600761337
fyi @boshek

Fix dev-docs workflow

---

_posts/2022-10-08-arrow-parquet-encoding-part-2.md

I was confused when I was reading this: `(0,2)`, `(2,3)`, and `(3,3)`.  I seems to me `child[2]` should be in `(2,3)` not `(3,3)`

[Website] Fix wrong example in 2022-10-08-arrow-parquet-encoding-part-2.md

---

_data/versions.yml
arrow.rdf

The Apache Community Development committee (ComDev) maintains a website [projects.apache.org](http://projects.apache.org/) which lists all ASF projects, and some basic details about them. These details are derived from DOAP (Description Of A Project) file that is maintained by each PMC.
Update the DOAP file for Arrow, which (in theory) drives the content of https://projects.apache.org/project.html?arrow, based on the output of the form at https://projects.apache.org/create.html. 
I have already updated [projects.xml](https://svn.apache.org/repos/asf/comdev/projects.apache.org/trunk/data/projects.xml) as described on https://projects.apache.org/create.html. See  https://github.com/apache/arrow/issues/25271#issuecomment-1735477349 for more details
N/A
No
* Closes: …

GH-25271: Update Apache Description Of A Project (DOAP) File

---

security.md

Update security page with reference to https://www.cve.org/CVERecord?id=CVE-2023-47248.
Also fix links to older CVEs to use the new official URLs.

[Website] Update security page with latest CVE

---

_includes/header.html
committers.md
community.md
faq.md

Resolve the broken link.
* https://github.com/apache/arrow-site/pull/436, This PR is the original.
* https://github.com/apache/arrow/issues/38851, This Issue is the original.

[Website] Fix broken link

---

_posts/2023-12-18-14.0.2-release.md

Website: Release 14.0.2 blog post

---

Gemfile
README.md

As suggested by @kou  in https://github.com/apache/arrow-site/pull/448#issuecomment-1878591082 let's use the latest Jekyll so the docs build with the latest ruby version
Note that @bkmgit has another PR that updates all dependencies in https://github.com/apache/arrow-site/pull/449

[Website]: Update to Jekyl `4.3.3`

---

_posts/2024-01-10-15.0.0-release.md

PR to start adding the blog post information for the Release 15.0.0
The 15.0.0 milestone with all the GitHub closed issues can be found here:
https://github.com/apache/arrow/milestone/56?closed=1

[Website] Version 15.0.0 blog post

---

powered_by.md

Hi - I built pantab about 6 years ago to write pandas DataFrames to a proprietary database owned by Tableau called Hyper. Over time hacking into pandas internals proved to be difficult, and I very recently swapped over to using nanoarrow and the Arrow PyCapsule interface with great results.
No hard feelings if there is not an appetite for this PR, but I figured I'd put it out there to celebrate the awesomeness of Arrow

Add Powered By note for pantab

---

.github/workflows/deploy.yml

fix #488
All docs/ contents are built by Sphinx in apache/arrow after #485.

Remove no longer needed build/docs/ sync

---

README.md

Remove outdated instructions for building Glib.  Refer to source repositories instead.

Update Build Instructions

---

.htaccess
_includes/header.html

Closes https://github.com/apache/datafusion/issues/10194
Closes https://github.com/apache/arrow-site/pull/502
Per @kou 's suggestion in https://github.com/apache/arrow-site/pull/502#issuecomment-2073432866, this PR adds a `.htaccess` file with a redirect from all `www.apache.org/datafusion` urls to `datadfusion.apache.org` urls (I think)
Documentaiton on these files is here: https://infra.apache.org/project-site.html
I don't really know how to test this other than "in production"

[Website] Add `.htaccess` to redirect  https://arrow.apache.org/datafusion to https://datafusion.apache.org/

---

.github/workflows/deploy.yml

Follow on to https://github.com/apache/arrow-site/pull/505 to actually copy the .htaccess file to the deployment site. Thanks to @kou  for noticing this https://github.com/apache/arrow-site/pull/505#issuecomment-2076086096

[Website]: Copy .htaccess to deploy site

---

.htaccess

Closes https://github.com/apache/datafusion/issues/10124
See https://github.com/apache/datafusion/issues/10124 -- basically we moved a URL that is bookmarked / comes up in google search. We need to redirect to the new location
Use the `.htaccess` process added in https://github.com/apache/arrow-site/pull/505 https://github.com/apache/arrow-site/pull/506 with @kou  to redirect to the new location

[Website]: Redirect old DataFusion CLI URL

---

docs/c_glib/index.html

The GLib front page: https://arrow.apache.org/docs/c_glib/
This is a manual workaround of
https://github.com/apache/arrow/issues/41405 for 16.0.0 release.
The new `index.html` is `docs/c_glib/index.html` in https://apache.jfrog.io/artifactory/arrow/docs/16.0.0/docs.tar.gz .

Use Sphinx generated page for the GLib front page

---

_posts/2024-04-20-16.0.0-release.md

I mistakenly left this bit in in the PR but this change is not what we'd consider a breaking change, see discussion in https://github.com/apache/arrow/issues/40607.

[Website] Remove breaking change from C++ section

---

_posts/2025-05-03-datafusion-tlp.md
_posts/2025-05-07-datafusion-tlp.md

This is a blog post about the move of DataFusion to a top level Apache project. I expect this is the last blog post on the arrow-site about DataFusion.
In my opinion, being part of Arrow has truly been a transformative experience for DataFusion 
Closes https://github.com/apache/datafusion/issues/10135
Closes https://github.com/apache/arrow-datafusion/issues/9691

[Website]: Blog announcing DataFusion top level project

---

.github/workflows/devdocs.yml

The doc build was changed in https://github.com/apache/arrow/pull/41455, we need a change here accordingly to ensure to keep updating the dev docs from that crossbow build.

Fix update of dev docs (test-ubuntu-*-docs -> test-debian-*-docs build change)

---

community.md

I believe the frequency of the Rust meeting is variable, not always biweekly. This updates the Meetings section of the Community page accordingly.

MINOR: Update community meeting frequencies

---

.htaccess

Closes #528 
This PR adds a line to  `.htaccess` file which will should redirect all arrow.apache.org/datafusion-python URLs to datafusion.apache.org/python.
This applies the same change as used for the top level `datafusion` https://github.com/apache/arrow-site/pull/505

[Website] Add .htaccess redirect for datafusion-python

---

_data/committers.yml

Adding missing committer entry with new affiliation.

Add Joel Lubinitsky to Arrow Committers

---

faq.md

This complements @AlenkaF's addition of a section about buffer compression to the format docs in https://github.com/apache/arrow/pull/43950.

[Website] Correct statement about compression in FAQ

---

_posts/2024-10-07-nanoarrow-0.6.0-release.md

This post adds an update for the nanoarrow 0.6.0 release!

Add nanoarrow 0.6.0 release post

---

_posts/2024-10-23-arrow-go-18.0.0-release.md

Adding a release post for the 18.0.0 release of Arrow Go, feel free to tag any additional reviewers I missed. Thanks!

Add Arrow Go 18.0.0 release post

---

_posts/2024-10-16-18.0.0-release.md
_posts/2024-10-28-18.0.0-release.md

Release blog post for 18.0.0.
Issues on the milestone are here: https://github.com/apache/arrow/milestone/64

Website: Add blog post for 18.0.0

---

_data/committers.yml

I became a committer of Apache Arrow on October 23, 2024. The mailing thread: https://lists.apache.org/thread/w66421ox74glnryot0vm0jjsvlxchg0z

[Website] Add Rossi Sun to committer list

---

_posts/2025-01-13-arrow-go-18.1.0.md

Didn't realize until after it deployed that the links weren't rendered correctly. So need to fix them (and then update the script to do this in the future).

minor: fix links in Go release

---

README.md
_config.yml
compose.yaml
install.md
run.sh

Fixes GH-578.
* Use meaningful "id" not "number" for link ID such as "arrow-rust" not "26"
* Add Go and Java to separated libraries
* Remove Java related description because Java was separated
* Remove Go related description because Go was separated
* Don't use newlines for a paragraph for all paragraphs
* Update supported Linux distributions
* Update available NuGet packages for C#
* Update available conda packages
* Update available MSYS2 packages
* Add Conan related information
* Update supported Ruby versions
It's not required but this also add Docker Compose configuration for local preview.

GH-578: [Website] Update the Install page

---

_posts/2025-01-16-19.0.0-release.md

The 19.0.0 release isn't completely ready to be announced yet but I wanted to get a start on the blog post. Will tag people here to contribute to sections.
See the [19.0.0 release milestone](https://github.com/apache/arrow/milestone/66?closed=1) for commits in this release.

Website: Add blog post for 19.0.0

---

_posts/2025-02-15-19.0.1-release.md
_posts/2025-02-16-19.0.1-release.md

Vote thread is still open, https://lists.apache.org/thread/3p0odso4hp6njtb7p7vyzzq0to68t6vx, but I'm just getting ahead of post-release tasks. This PR is currently a draft.

[Website] Add blog post for Arrow 19.0.1

---

_includes/top.html

This reverts the addition of the  `<meta http-equiv="Content-Security-Policy" ...` element in #595 because it caused more errors than it fixed.
I will open a separate PR to try to implement a fix that doesn't cause more errors.

Revert addition of Content-Security-Policy meta tag

---

.htaccess

It appears that the previous attempts were not having the expected effect because the ASF is already setting a Content-Security-Policy header which this was not overriding. The header that the ASF is setting is:
```
default-src 'self' data: blob: 'unsafe-inline' https://www.apachecon.com/ https://www.communityovercode.org/ https://analytics.apache.org/;
script-src 'self' 'unsafe-inline' 'unsafe-eval' https://analytics.apache.org/;
style-src 'self' 'unsafe-inline' data:;
frame-ancestors 'self';
frame-src 'self' data: blob:;
img-src 'self' data: https://*.apache.org/;
worker-src 'self' data: blob:;
```
This unsets the ASF-set CSP header and sets a new one that is based on the ASF one with additions.

Try fix Content Security Policy errors (take 5)

---

_includes/top.html

As a follow-on to https://github.com/apache/arrow-site/pull/611, this adds a `link` tag to our head which should support feed autodiscovery.

Website: Support feed autodiscovery

---

_posts/2022-11-07-multi-column-sorts-in-arrow-rust-part-2.md

As mentioned in the previous [comment](https://github.com/apache/arrow-rs/issues/4639#issuecomment-2705901229), the dictionary encoding example contains inaccuracies.

Fix illustration for dict encoding in row format

---

.htaccess

This PR updates the .htaccess file to allow the kapa.ai bot to work correctly.  The [Infra guidance](https://infra.apache.org/csp.html) notes that external resources are disallowed for providers we **do not** have a DPA with, but kapa.ai **does** [have one with the ASF](https://privacy.apache.org/faq/committers.html) so this should be all good.

Update .htaccess file to allow kapa.ai bot to work

---

.htaccess

This reverts #619. The Arrow site began to serve an HTTP 500 error some time after #619 was merged. Possibly this was a coincidence but I'm quickly merging this revert to see if that brings the site back up.

Revert addition to .htaccess

---

.htaccess

Enabling the kapa.ai bot, this time using an Infra-suggested CSP update (see https://issues.apache.org/jira/browse/INFRA-26638).

Update .htaccess to allow kapa.ai bot

---

install.md

Fixes GH-636
We use https://repo1.maven.org/maven2/org/apache/arrow/ not https://apache.jfrog.io/artifactory/arrow/ for APT/Yum repositories.
See also: https://github.com/apache/arrow/issues/40760
All contents are already copied to
https://repo1.maven.org/maven2/org/apache/arrow/ . So we can use it before we release 20.0.0.

Use repo1.maven.org not apache.jfrog.io in the install page

---

community.md

The repositories that did not have GitHub discussions have been updated to also have GitHub discussions enabled.
This PR updates the links and some minor details on the wording to remove the conditional.
See:
- https://github.com/apache/arrow-java/pull/710
- https://github.com/apache/arrow-julia/pull/546
- https://github.com/apache/arrow-go/pull/353

[Website] Update repositories that did not have GitHub discussions

---

install.md

This reverts commit ad535796c46714c312cb538a6261616ecf77e44f.
It seems that we can't use repo1.maven.org for APT/Yum repositories. See also: https://github.com/apache/arrow/issues/46083
This also has a change that replaces apache.jfrog.io with packages.apache.org. packages.apache.org is an alias of apache.jfrog.io. It'll be better that we use .apache.org host name.

Revert "Use repo1.maven.org not apache.jfrog.io in the install page (#637)"

---

_posts/2025-05-13-arrow-java-18.3.0.md

We need an empty line between a list markup and a section markup to avoid putting a section into a list.

post: Fix a markup in Apache Arrow Java 18.3.0

---

_includes/header.html

It is necessary to update Swift URL due to move the repository.
https://github.com/apache/arrow/pull/46804
This PR wait  to resolve   https://github.com/apache/arrow-swift/issues/9 issue.
Because http://arrow.apache.org/docs/swift/ not available yet.

Update Swift links

---

Gemfile
_config.yml

Makes link opening behavior consistent for internal and external links. Internal links work as before and now external links (any non-relative URL) have `target="_blank" rel="noopener"` set. Content authors can override this by using inline HTML.
Closes https://github.com/apache/arrow-site/issues/677

[Website] Always open external links with target=_blank

---

_config.yml

Fixes GH-680.
We need `UNSAFE` option for raw `<table>`.

Add UNSAFE option to Jekyll config to allow raw HTML

---

visual_identity.md

I think the recent markdown parser change made it so we can't do headers like this anymore,
```
```
This fixes the [current rendering](https://arrow.apache.org/visual_identity/) which has headers that look like this:
> Design of the logo {#design}
and restores the internal document anchors. A better solution might be to look into a Jekyll plugin that automatically enables anchors on headers and ToCs.
Closes #695

GH-695: [Website] Fix anchors on visual identity page
