index.html

Most minimalistic update to have at least a 0.2.0 release.
cc @julienledem @wesm

Add 0.2.0 release

---

powered_by/index.html

Quick fix for https://github.com/apache/arrow/issues/5156. I'll make the change on master in the source too.

Fix PR link for powered_by page

---

powered_by.md

See https://github.com/apache/arrow/issues/5156 and https://github.com/apache/arrow-site/pull/13

Fix PR link on powered_by page in source

---

committers.html

I'd like to add new committers on the list.

ARROW-6505: [Website] Add new committers

---

_config.yml
scripts/merge_pr.py

We don't publish files under scripts/. merge_pr.py is an internal
script. It should not be published.

ARROW-6822: [Website] Move merge_pr.py to scripts/

---

_layouts/home.html

Add GitHub star and Twitter follow buttons

---

_layouts/home.html
css/main.scss

Minor tweaks to the newly added badges. See https://enpiar.com/arrow-site/ and compare to arrow.apache.org

Adjust positioning of badges

---

powered_by.md

Thanks you for the awesome library!

Add aws-data-wrangler to "Powered by" section

---

faq.md

This question comes up occasionally as people try and learn Arrow and fit it into their mental model so hopefully this will help.

ARROW-11911: [Website] Add protobuf vs arrow to FAQ

---

powered_by.md

Thank you for the great project!

Add HASH to 'powered by' page

---

_posts/2021-04-26-4.0.0-release.md

Please fill in the various sections as best you can. Thanks!

4.0 release blog post

---

_posts/2021-04-26-4.0.0-release.md

MINOR: [Website] Fix a typo

---

.asf.yaml

See also: https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features

ARROW-12662: [Website] Force to use squash merge

---

powered_by.md

This PR proposes adding Polars to the list of projects that use Apache Arrow.

Add polars project

---

_posts/2021-07-20-5.0.0-rs-release.md

Proposed blog post for apache arrow 5.0 rs release
Based on content from https://docs.google.com/document/d/1QVvngReUcAtBf7Tz_TAHZZeXT9W1mha3UwgF_uGys9E/edit

Rust 5.0.0 release blog

---

_posts/2021-07-20-5.0.0-release.md

[Website] Fix 5.0.0 blog post date

---

_data/committers.yml

Adding myself to the committers list (it seems like that's what i'm supposed to do according to the README?)
CC @emkornfield

MINOR: [Website] Update committers.yml

---

_data/committers.yml

Apologize that I was being lazy and tried to use Github's web UI to create this commit. But I forgot Github defaults to commit to the master branch directly. So 18850af65bb79500349aaca1543fcbcd11813ead ended up in the master branch without code review. I have since pushed a commit to revert that commit.
I am sending a PR for the same commit so it can be reviewed properly by the community.

MINOR: [Website] Add QP to committers.yml

---

powered_by.md

Python team at Esri would like to add ArcPy to the list on https://arrow.apache.org/powered_by/.
hziegler@esri.com

Add ArcPy to powered_by.md

---

_posts/2021-12-3-arrow-duckdb.md

@wesm caught this, cc @pdet @jonkeane

Add "Apache" to title

---

_data/committers.yml

See mailing list thread: https://lists.apache.org/thread/ntx3251pwnbd759kghbyjn4s31kcf8v2
cc @Dandandan

Add Daniël Heres to list of PMC

---

docs/r/versions.json

A follow-up on https://github.com/apache/arrow/pull/12172 which added this to the main repo. Adding this already here allows to test it with the nightly dev docs.

ARROW-14338: [Docs][R] Add R versions.json

---

docs/r/news/index.html

https://github.com/apache/arrow/commit/526fa070c82c0e1c6d26a4c1d06a591b37c05011 apparently did not make it into the release tag

MINOR: Backfill R news for 8.0.0 release

---

_posts/2022-05-05-8.0.0-release.md
_posts/2022-05-15-8.0.0-release.md

PR to start adding the blog post information for the Release 8.0.0

Version 8.0.0 release blog post

---

_posts/2022-05-16-datafusion-8.0.0.md

Based on crowd-sourced draft at https://docs.google.com/document/d/16PhXQs4s2HJNPLydy5J5pqXnefI-iR3VxGqrO497M08/edit?usp=sharing

ARROW-16595: [WEBSITE] DataFusion 8.0.0 release blog post

---

_data/committers.yml

Update mrkn's affiliation

---

_data/committers.yml

Update @viirya  to PMC part of list per https://lists.apache.org/thread/dx3tm476b5kmdtrzh80b2zd0pf7k5q85

Update committer information for viirya

---

_data/committers.yml

Update information for @westonpace to reflect new role per https://lists.apache.org/thread/ld23csmg31x4lvtpnyzp6v5dz8ysqv1h

Update committer information for Weston Pace

---

_data/committers.yml

Add @yahoNanJing to committer list on https://arrow.apache.org/committers/
per https://lists.apache.org/thread/v4x9mgttco8t06dxshw1o2zwlmldgz69

Add Yanghong Zhong as committer

---

.github/workflows/deploy.yml

Per conversation at https://github.com/apache/arrow-site/commit/584512f60d05e7e866a63c9da4ba3e11b09d7ec6#commitcomment-84944520

ARROW-17878: [Website] Exclude Ballista docs from being deleted

---

_data/committers.yml

Update role listed on https://arrow.apache.org/committers/ to PMC per https://lists.apache.org/thread/x4jxq8yrgsp3pqsty4rzz3jydow3kvz3

[MINOR] Update tustvold role to PMC

---

_posts/2022-10-01-arrow-parquet-encoding-part-1.md

See rationale on https://issues.apache.org/jira/browse/ARROW-17907

ARROW-17908: [Website] Arbitrarily Nested Data in Parquet and Arrow: Part 1: Introduction

---

_posts/2022-10-05-arrow-parquet-encoding-part-1.md

Fix some issues with: https://github.com/apache/arrow-site/pull/245
Date needs to be updated
Title doesn't display: 🤦

ARROW-17908: [Website] fix date + title for Arbitrarily Nested Data in Parquet and Arrow: Part 1: Introduction

---

_posts/2022-10-05-arrow-parquet-encoding-part-1.md

Third and (what I hope is) final PR in a series https://github.com/apache/arrow-site/pull/250
I have also figured out how to render this site locally (see https://github.com/apache/arrow-site/pull/251)  so I can test somewhere other than production next time

[Minor] Tweak markdown and fix typo

---

README.md
Rakefile

I find myself not wanting / able to mess with a ruby installation locally, so here is how to build / preview the site using docker. 
To try and avoid blunders like https://github.com/apache/arrow-site/pull/250

[MINOR] Add instructions for building site locally using docker

---

_posts/2022-10-25-datafusion-13.0.0.md

[MINOR] Fix broken markdown in Apache Arrow DataFusion 13.0.0 Project Update

---

_posts/2022-10-17-10.0.0-release.md
_posts/2022-10-31-10.0.0-release.md

PR to start adding the blog post information for the Release 10.0.0

[Website] Version 10.0.0 release blog post

---

_posts/2022-11-07-multi-column-sorts-in-arrow-rust-part-2.md

Follow on to https://github.com/apache/arrow-site/pull/264
Correct's the publish date

Fix post date for Fast and Memory Efficient Multi-Column Sorts in Apache Arrow Rust, Part 2

---

_posts/2022-11-07-multi-column-sorts-in-arrow-rust-part-2.md

Reported by @doki23 in https://github.com/apache/arrow-rs/issues/3059

MINOR: [Website] Fix incorrect diagram for 2022-11-07-multi-column-sorts-in-arrow-rust-part-2.md

---

_data/committers.yml

Update to reflect changes in PMC membership. See https://lists.apache.org/thread/wpt8ozp8g9bgkvkpf3643ot0rqszrot8

[Website]: Add Kun Liu to the PMC list

---

_data/committers.yml

Affiliation for Ben Baumgold is missing

ARROW-18426: [Website] Update committer and PMC list

---

_data/committers.yml

Add Jacob Wujciak to committer list as per https://lists.apache.org/thread/x9nmf01yz8zwrc7c8swkkwo9wzttn937.

[Website] Add Jacob Wujciak to committer list

---

docs/r/versions.json

GH-291: [R] Update versions.json for 10.0.1

---

powered_by.md
use_cases.md

We have been integrating Apache Arrow across all of our projects during 2022 and hoping to share them with the broader community.

[Website] Add links to UKV

---

_data/committers.yml

Update https://arrow.apache.org/committers/ Per https://lists.apache.org/thread/0cqwzhnftbnbbf3x1o209dnkoz5gbqd3
@avantgardnerio what, if anything, would you like your affiliation to be?

[WEBSITE]: Add Brent Gardner / avantgardnerio to committers list

---

_data/committers.yml

Update https://arrow.apache.org/committers/ Per https://lists.apache.org/thread/o2jtvwz6v027x7k3pgdrsly2pznbrd3k
@jackwener  what, if anything, would you like your affiliation to be?

[WEBSITE]: Add Jie Wen / jackwener to commiters list

---

_data/committers.yml

Update PMC chair on website. 
Reference to dev list:  https://lists.apache.org/thread/f46owgtf0c0888tb7qjjrstrgth42181

[WEBSITE]: Update PMC chair

---

_posts/2022-12-26-querying-parquet-with-millisecond-latency.md

Just some minor things I noticed whilst reading the blog again

Minor tweaks to querying parquet with millisecond latency

---

_data/committers.yml

Per https://lists.apache.org/thread/yrbyy2blgpltv02c6x8jty5nw5pofnkv
Update @wjones127  to be listed as on the PMC

[WEBSITE]: Update Will Jones membership to PMC

---

powered_by.md

This adds HF `datasets` to the list of projects using Arrow. (https://huggingface.co/docs/datasets/about_arrow)

Add Hugging Face Datasets to powered_by.md

---

_data/committers.yml

Add @waynexia to the list of Apache Arrow committers according to https://lists.apache.org/thread/52m6khs1wd64ggmoj19zkps0r25x5zvj

[Website] Add Ruihang Xia to committer list

---

_data/committers.yml

Per https://lists.apache.org/thread/b1bq6ldl26ts14nm6kp8pjxm7btllgs1 add @mingmwang to the list of Apache Arrow committers
@mingmwang, can you please confirm that your affiliation is correctly listed?

[WEBSITE]: Add mingmwang to list of committers

---

_posts/2023-05-04-adopting-apache-arrow-at-cloudquery.md

Update post from https://github.com/apache/arrow-site/pull/348 to reflect actual publish date

[Minor]: Update date on cloud query post

---

_data/committers.yml

Add `mneumann`/@crepererum to committer list according to https://lists.apache.org/thread/275bljcbg23w2nzfpqr64qf5zzzy49rp

[Website] Add Marco Neumann to committer list

---

_data/committers.yml

MINOR: Update some affiliations

---

_data/committers.yml

Update the website's list of committers https://arrow.apache.org/committers/ to include @mustafasrepo and @ozankabak
Email references:
https://lists.apache.org/thread/7p84z40spn2727cr6znrhqb4jdmw70y6
https://lists.apache.org/thread/z5z7y0dhcvno9d7s8xpyk77zhfnqztz1

[Website]: Add mustafasrepo and ozankabak to committers list

---

_data/committers.yml

Update the website per: https://lists.apache.org/thread/10x9vfl5pl892k5tovwf145vbsw0378r to list @jackwener  as on the PMC

[WEBSITE]: Update role of Jie Wen to PMC

---

_data/committers.yml

Update website to match new role for @paleolimbot : https://lists.apache.org/thread/ddvlhccpghr3wc2gs2l6dnr4wbxs4hhh

[WEBSITE]: update Dewey Dunnington role to PMC

---

community.md

MINOR: Fix typo on community.md

---

_data/committers.yml

Add `kevingurney`/@kevingurney to committer list according to https://lists.apache.org/thread/8c1jwwosqry9cbk01kdh73k29nhd25ll

[Website] Add Kevin Gurney to committer list

---

_data/committers.yml

Related to https://github.com/apache/arrow-site/issues/383
Add Gang Wu to committers list per https://lists.apache.org/thread/sbc7kyjgv3bwptlydr8wspnd6zbzptvv
@wgtmac  what affiliation would be good to list for you?

[Website] Add Gang Wu to Committers list

---

_posts/2023-07-17-13.0.0-release.md
_posts/2023-08-24-13.0.0-release.md

PR to start adding the blog post information for the Release 13.0.0
The 13.0.0 milestone with all the GitHub closed issues can be found here:
https://github.com/apache/arrow/milestone/53?closed=1

[Website] Version 13.0.0 blog post

---

powered_by.md

Add OpenObserve, A project, powered by Apache Arrow

Add OpenObserve

---

_posts/2022-10-08-arrow-parquet-encoding-part-2.md

Found some typos while I am reading the blog.

[Website] Fix some typos

---

_data/committers.yml

cc @Dandandan  -- is this correct?

MINOR: [WEBSITE] Update affiliation for Daniël Heres

---

_data/committers.yml

cc @yjshen -- is this affiliation correct?

MINOR: [WEBSITE] Update affiliation of Yijie Shen

---

_data/committers.yml

Per https://lists.apache.org/thread/9plwr2w6hc9ktq47351pgn5m80gz8dv1, add @comphead  to the list at https://arrow.apache.org/committers/
cc @comphead  please let me know how you would like to list your affiliation (it can be `None` for example, if there is no larger organization that is affiliated with your contributions to this project)

[WEBSITE]: Add Oleks V / comphead to commiters list

---

_data/committers.yml

cc @avantgardnerio  -- is this the correct affiliation?

MINOR: [WEBSITE] Update Affiliation for Brent Gardner

---

_data/committers.yml

Update https://arrow.apache.org/committers/ to reflect change in committers list
See https://lists.apache.org/thread/nmsqt8wcphysly90l0conmccrqjk3pdo

[WEBSITE]: Add Curt Hagenlocher to committers list

---

_data/committers.yml

I noticed this while working on https://github.com/apache/arrow-site/pull/420# so figured I would make a quick PR to update the affiliation data.
cc @sunchao

[WEBSITE]: Update Affiliation for sunchao

---

_posts/2023-10-11-14.0.0-release.md
_posts/2023-11-01-14.0.0-release.md

PR to start adding the blog post information for the Release 14.0.0
The 14.0.0 milestone with all the GitHub closed issues can be found here:
https://github.com/apache/arrow/milestone/55?closed=1

[Website] Version 14.0.0 blog post 

---

_data/committers.yml

Per https://lists.apache.org/thread/zmom0gcvnld7phb43bjwzm8wf8x5zsmo
Update website to show @raulcd  as PMC membr.

[Website]: Add raulcd as PMC

---

_data/committers.yml

Add myself to the committers list, per https://lists.apache.org/thread/yk01t5j0p26vjfr4vzxv1zls5zk2hk4v

Add James Duong to committers

---

_data/committers.yml

Add me as a committer
I work for a startup, so just fill affiliation as unknown, thanks!

Add Xuwei Fu as committer

---

_posts/2023-08-05-datafusion_fast_grouping.md

Ensure rss feed validates correctly
Closes https://github.com/apache/arrow-site/issues/460

Fix formatting error

---

powered_by.md

Follow up to https://github.com/apache/arrow-site/pull/471 this wasn't meant to be there

Fix errant line with pantab note

---

powered_by.md

Included details about iceburst.io

Add iceburst to powered by list

---

_data/committers.yml

Add per https://lists.apache.org/thread/xwjg62x0bzj5bgops2yqsfzh3nqcwy73 
🎉

[Website] Add Jay Zhan as committer

---

powered_by.md

I've added a new project that in my opinion should be included, since it fully integrates with Apache Arrow, and it provides a great tool for software developer and data engineers.
The project name is called "delta rs", more about that into the pull request code.
Been forwarded here after I've opened an issue on apache/arrow.

[Website]: Add delta-rs to the Powerd by page

---

_posts/2024-03-07-15.0.1-release.md

Website: Release 15.0.1 blog post

---

.htaccess

Try to fix https://github.com/apache/datafusion/issues/10124, try two

[Website]: Different redirect order for datafusion CLI

---

_data/committers.yml

Reference: https://lists.apache.org/thread/0lo21qcndbyq6nrtjmqxotsk58dwqcfp
Add new committer to https://arrow.apache.org/committers/ page
@amoeba - please can you verify this information is correct?

[Website] Add new committer: Bryce Mecum

---

_data/committers.yml

I was accepted as a committer to the Arrow project on May 7, 2024. See https://lists.apache.org/thread/9ysqj4qbmhhl8lp101ltq62ndf8vgsq3.

Add Dane Pitkin to committers list

---

docs/python/install.html

My attempt at updating docs/python/install.html with teh changes in https://github.com/apache/arrow/pull/41135.
I generated the docs locally, copied the generated install.html into arrow-site, and then only committed the hunks I know changed. I didn't commit the entire changed file since the diff included many more changes, some of which looked like they'd break the page.

MINOR: Update docs/python/install.html with GH-41105

---

powered_by.md

Org name: Spice AI
Org URL: https://spice.ai
Project URL: https://github.com/spiceai/spiceai
Arrow components: Arrow, Flight, FlightSQL, ADBC

Add Spice.ai OSS to powered_by.md

---

_posts/2024-05-27-nanoarrow-0.5.0-release.md

Fix typo in nanoarrow 0.5.0 post date

---

_data/committers.yml

I was accepted as a committer to the Apache Arrow project on April 11, 2024.
See the mailing thread below:
https://lists.apache.org/thread/797fx29557x5g8t404nqmm58mmlj7sjq

[Website] Add Sarah Gilmore to committer list

---

powered_by.md

Org name: Squey
Org URL: https://squey.org
Project URL: https://gitlab.com/squey/squey
Arrow components: RecordBatch, Compute

Add Squey to powered_by.md

---

community.md

Add PyArrow dev meetings to the list.

Add PyArrow development meeting to the community page

---

_layouts/home.html
index.html

Part 1 of 2 of https://github.com/apache/arrow/issues/44474.
This updates the Apache Arrow project description that appears prominently at the top of the [website](https://arrow.apache.org).

GH-44474: [Website] Improve project description

---

_data/committers.yml

Update website with new PMC chair, per https://lists.apache.org/thread/t96pjllohl6kkd4pxq4031cvdj064sfd

[Website] Update Chair to Neal Richardson

---

package-lock.json
package.json

This reverts commit bc43ff0dc626b52e84c6643e37c20b2d731ee7bf.

Website: Revert "Bump bootstrap from 4.6.0 to 5.0.0 (#559)"

---

_data/committers.yml

We both work for QuantStack now.

Update Raul's affiliation and mine

---

.github/workflows/deploy.yml
_config.yml

Fixes GH-588.
We don't need to use `cp` manually.

Use `include` in `_config.yml` for `.asf.yaml` and `.htaccess`

---

_data/versions.yml
_release/19.0.1.md
_release/index.md

This includes a commit with two manually tweaks to the generated output.

[Website] Release note 19.0.1

---

_config.yml
arrow.rdf
faq.md
index.html
overview.md

This updates the project description in a few places that #549 missed.
See the rationale at https://github.com/apache/arrow/issues/44474.

Improve project descriptions

---

_data/committers.yml

Per https://lists.apache.org/thread/r4f42jvkklkfz1t595hwjl40n6nqqp5b let's add @mbrobbel to the website

[Website] Add `mbrobbel` to the committers list

---

Gemfile

Add base64 and csv to Gemfile

---

_posts/2025-07-02-nanoarrow-0.7.0-release.md

Release post for nanoarrow 0.7.0

---

_release/index.md

Minor fix on Markdown to fix link
Closes #674

Fix link for 18.1.0 release

---

.github/workflows/devdocs.yml

Remove old contents in docs/dev/

---

.github/workflows/deploy.yml

Fixes #687
We need to run "git config" in a directory that has ".git/".

Fix asf-site deploy CI

---

.github/workflows/pr_comment.yml

Comment preview URL automatically

---

community.md

This better reflects the current (in)frequency of these meetings.

Update list of meetings on Community page
